Changes to be committed: 	modified:   .clang-format 	new file:   .clangd 	deleted:    .notclangd 	new file:   .vscode/settings.json 	deleted:    ROADMAP 	modified:   TODO.txt 	modified:   config.h 	modified:   install 	modified:   src/cpp/cfg.cpp 	modified:   src/cpp/chars.cpp 	modified:   src/cpp/color.cpp 	modified:   src/cpp/cut.cpp 	modified:   src/cpp/event.cpp 	modified:   src/cpp/files.cpp 	modified:   src/cpp/global.cpp 	modified:   src/cpp/gui.cpp 	new file:   src/cpp/gui/guicallbacks.cpp 	new file:   src/cpp/gui/guiutils.cpp 	new file:   src/cpp/gui/guiwinio.cpp 	modified:   src/cpp/help.cpp 	modified:   src/cpp/history.cpp 	modified:   src/cpp/language_server/preprossesor.cpp 	modified:   src/cpp/lines.cpp 	modified:   src/cpp/move.cpp 	modified:   src/cpp/nano.cpp 	modified:   src/cpp/nstring.cpp 	modified:   src/cpp/prompt.cpp 	modified:   src/cpp/rcfile.cpp 	modified:   src/cpp/render.cpp 	modified:   src/cpp/search.cpp 	modified:   src/cpp/signal.cpp 	modified:   src/cpp/syntax.cpp 	modified:   src/cpp/text.cpp 	modified:   src/cpp/threadpool.cpp 	modified:   src/cpp/utils.cpp 	modified:   src/cpp/winio.cpp 	modified:   src/cpp/words.cpp 	new file:   src/include/c_defs.h 	modified:   src/include/c_proto.h 	modified:   src/include/config.h 	modified:   src/include/constexpr_def.h 	modified:   src/include/definitions.h 	modified:   src/include/prototypes.h 	modified:   src/include/task_types.h

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,34 @@
 #!/bin/bash
 
+CONFIG_FILE="config.h"
+GLFW_DEFINE="#define HAVE_GLFW 1"
+
+# Check if this has already been checked and defined in the config file.
+if ! grep -qF "$GLFW_DEFINE" "$CONFIG_FILE" 2>/dev/null; then
+cat <<EOF > test_glfw.c
+#include "src/lib/include/GLFW/glfw3.h"
+int main() {
+	if (!glfwInit()) {
+		return -1;
+  }
+  glfwTerminate();
+  return 0;
+}
+EOF
+  if gcc -o test_glfw test_glfw.c src/lib/bin/libglfw3.a -lm 2>/dev/null; then
+    echo "" >> "$CONFIG_FILE"
+    echo "" >> "$CONFIG_FILE"
+    echo "/* This is defined by the installer if glfw is installed staticly and localaly. */" >> "$CONFIG_FILE"
+    echo "$GLFW_DEFINE" >> "$CONFIG_FILE"
+    rm -f test_glfw
+  else
+    echo "Could not find static glfw lib installed.  Use 'AmakeCpp --lib glfw-static' to install."
+  fi
+  rm -f test_glfw.c
+fi
+
 AmakeCpp --test
-sudo AmakeCpp --link --bin /usr/lib/Mlib.a
+sudo AmakeCpp --link --bin -lGLEW -lGL -lfreetype /usr/lib/Mlib.a /usr/lib/freetype-gl.a
 if [ -f build/bin/NanoX ]; then
   sudo cp build/bin/NanoX /usr/bin/nanox
 fi
